# Generated by Django 4.0.2 on 2022-02-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('photo', models.ImageField(upload_to='Realtors/%Y/%m/%d/')),
                ('description', models.TextField(null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=120)),
                ('date_hired', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
