# Generated by Django 4.0.4 on 2022-04-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Realtors',
            new_name='Realtor',
        ),
        migrations.AlterModelOptions(
            name='realtor',
            options={'verbose_name_plural': 'Realtors'},
        ),
    ]
